-- This file has been generated by Dungeon Editor 2.2.4

defineObject{
	name = "boat_small",
	baseObject = "base_floor_decoration",
	components = {
		{
			class = "Model",
			model = "mod_assets/models/boat.fbx",
			dissolveStart = 6,
			dissolveEnd = 9,
			staticShadow = true,
		},
	},
	editorIcon = 108,
	minimalSaveState = true,
}