-- This file has been generated by Dungeon Editor 2.2.4

defineObject{
	name = "boat_small",
	baseObject = "base_floor_decoration",
	components = {
		{
			class = "Model",
			model = "mod_assets/models/boat.fbx",
			dissolveStart = 6,
			dissolveEnd = 9,
			staticShadow = true,
		},
	},
	editorIcon = 108,
	minimalSaveState = true,
}

defineObject{
    name = "rubble_pedestal",
    baseObject = "pedestal",
    components = {
        {
            class = "Surface",			
            offset = vec(0, 0.85, 0),
			size = vec(1, 0.65),			
            onAcceptItem = function(self, item)
                return (self:count() == 0 and item.go.name == "pickaxe")
            end
        }
    }
}

defineObject{
	name = "surface_catacomb_alcove_lower",
	baseObject = "base_wall",
	components = {
		{
			class = "Surface",
			offset = vec(0, 0.85, 0.2), 
			size = vec(2, 0.2),
			--debugDraw = true,
		}, 
		{
			class = "Clickable",
			offset = vec(0, 0.85, 0.2), 
			size = vec(2, 0.2),
			-- debugDraw = true,
		},		
        {
			class = "Light",
			range = 3.5,
			color = vec(0, 1, 0),
			brightness = 7,
			castShadow = true,
			staticShadows = true,
			shadowMapSize = 256,
			--fillLight = true,
			offset = vec(0, 0.85, 0.2),
			onUpdate = function(self)
				local noise = math.noise(Time.currentTime()*3 + 123) * 0.5 + 0.9
				self:setBrightness(noise * 10)
			end,
		},
	},
	editorIcon = 92,
	minimalSaveState = false,
}
defineObject{
	name = "surface_catacomb_alcove_upper",
	baseObject = "base_wall",
	components = {
		{
			class = "Surface",
			offset = vec(0, 1.85, 0.2), 
			size = vec(2, 0.2),
			--debugDraw = true,
		}, 
		{
			class = "Clickable",
			offset = vec(0, 2, 0.2), 
			size = vec(2, 0.2),
			-- debugDraw = true,
		},        
        {
			class = "Light",
			range = 3.5,
			color = vec(0, 1, 0),
			brightness = 7,
			castShadow = true,
			staticShadows = true,
			shadowMapSize = 256,
			--fillLight = true,
			offset = vec(0, 1.85, 0.2),
			onUpdate = function(self)
				local noise = math.noise(Time.currentTime()*3 + 123) * 0.5 + 0.9
				self:setBrightness(noise * 10)
			end,
		},
	},
	editorIcon = 92,
	minimalSaveState = false,
}