-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom sound definitions here
defineSound{
	name = "mining",
	filename = "mod_assets/sounds/mining.wav",
	loop = false,
	volume = 0.25,
	minDistance = 5,
	maxDistance = 12,
}

defineSound{
    name = "evil_whisper",
    filename = "mod_assets/sounds/evil_whisper.wav",
    loop = true,
    volume = 0.75,
    minDistance = 1,
    maxDistance = 3
}

defineSound{
    name = "charge_up",
    filename = "mod_assets/sounds/charge_up.wav",
    loop = false,
    volume = 1,
    minDistance = 5,
    maxDistance = 12
}