-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom sound definitions here
defineSound{
	name = "mining",
	filename = "mod_assets/sounds/mining.wav",
	loop = false,
	volume = 0.25,
	minDistance = 5,
	maxDistance = 12,
}